language: node_js
sudo: false
node_js:
  - "0.12"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g karma
  - npm install -g gulp
  - npm install -g bower
  - ./nodeserver.sh > /dev/null &
install:
  - npm install
  - bower install
before_script:
  - bower install
  - npm install
script: gulp build